### Регистрация первого родителя
POST {{host}}/api/v1/auth/register
Content-Type: application/json
Accept: application/json

{
  "login": "parent@example.com",
  "password": "password123",
  "display_name": "Родитель"
}

### Вход по логину и паролю
POST {{host}}/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "login": "parent@example.com",
  "password": "password123"
}
